
dist: bionic
sudo: required

language: python
python:
  - "3.6"

services:
  - docker
install:
  - 'pip install pipenv'
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make deploy
